apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.gateway.tlsSecretName }}
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Files.Get .Values.gateway.tls.certFile | b64enc }}
  tls.key: {{ .Files.Get .Values.gateway.tls.keyFile | b64enc }}
